services:

  laravel_tcc_nvt:
    container_name: laravel_tcc_nvt
    build: .
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 8000:80
      - 3000:5173
  
  mysql_db:
    image: mysql:latest #escolher uma versão fixa caso for usar o banco
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_tcc_nvt
    ports:
    - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql_db
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
      - PMA_PORT=3306